version: '3.8' 

services:
  apache:
    build: ./apache
    container_name: lamp_apache
    volumes:
      - ./studenti:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=service_flow_db
    ports:
      - "8081:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: lamp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service_flow_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: